// Validate the HTML the app actually produces: index.html plus the rendered DOM of every route.
// (Single-page apps build most markup in JavaScript, so validating the source file alone would miss it.)
import { readFile, writeFile } from 'node:fs/promises';
import { HtmlValidate } from 'html-validate';
import { start } from './helpers.mjs';

const { base, browser, check, finish } = await start();
const validator = new HtmlValidate({ extends: ['html-validate:recommended'], rules: {
  'no-trailing-whitespace': 'off', 'void-style': 'off',
  // outerHTML always writes boolean attributes as required="" / hidden="": a serialisation artefact, not a real problem
  'attribute-boolean-style': 'off', 'attribute-empty-style': 'off',
  // checkbox groups legitimately share one name (read back with FormData.getAll)
  'form-dup-name': ['error', { shared: ['radio', 'button', 'reset', 'submit', 'checkbox'] }],
  'prefer-native-element': 'error', 'no-inline-style': 'error',
} });

const ctx = await browser.newContext({ viewport: { width: 1280, height: 900 } });
const page = await ctx.newPage();
const works = JSON.parse(await readFile('tests/fixtures/openalex-works.json', 'utf8'));
const crossref = JSON.parse(await readFile('tests/fixtures/crossref-works.json', 'utf8'));
const CORS = { 'access-control-allow-origin': '*', 'content-type': 'application/json' };
await ctx.route('https://api.openalex.org/**', (r) => r.fulfill({ status: 200, headers: CORS, body: JSON.stringify(works) }));
await ctx.route('https://api.crossref.org/**', (r) => r.fulfill({ status: 200, headers: CORS, body: JSON.stringify(crossref) }));

await page.goto(`${base}#/dashboard`);
const id = await page.evaluate(async () => {
  const { getRepo } = await import('/js/db/index.js'); const repo = await getRepo();
  const A = await repo.projects.create({ name: 'AI-assisted coding' }); const q = await repo.questions.create(A.id, { text: 'Does AI code generation improve productivity?' });
  await repo.papers.saveToProject(A.id, { id: 'p1', title: 'Productivity Assessment', authors: ['A'], year: 2022, doi: '10.1/x', abstract: 'Abstract.', url: 'https://example.org', sources: ['openalex'], isOa: true, oaStatus: 'green' });
  await repo.papers.saveReview(A.id, 'p1', { status: 'read', notes: 'n' });
  await repo.evidence.create({ projectId: A.id, paperId: 'p1', researchQuestionId: q.id, relationship: 'supports', evidence: 'e', interpretation: 'i', location: 'p. 1', tags: 'x' });
  return A.id;
});

const routes = ['#/dashboard', '#/projects', `#/projects/${id}`, '#/discover', '#/discover?q=copilot', '#/library', `#/library/p1?project=${id}`, `#/library/p1?tab=review&project=${id}`, `#/library/p1?tab=evidence&project=${id}`, '#/evidence', `#/matrix?project=${id}`, `#/progress?project=${id}`, '#/backup', '#/nothing'];
const problems = [];
let pages = 0;
for (const hash of routes) {
  await page.goto(`${base}${hash}`);
  await page.reload();
  await page.waitForFunction(() => !document.querySelector('[aria-busy="true"]'));
  if (hash.includes('q=')) await page.waitForSelector('.paper');
  await page.waitForTimeout(100);
  // Serialise the live DOM, minus the browser-injected axe/test scaffolding.
  const html = `<!DOCTYPE html>\n${await page.evaluate(() => document.documentElement.outerHTML)}`;
  const report = await validator.validateString(html, hash);
  pages += 1;
  for (const r of report.results) for (const m of r.messages) problems.push(`${hash} (${m.ruleId}) line ${m.line}: ${m.message}`);
}
const unique = [...new Set(problems)];
await writeFile('docs/testing/html-validation.md', `# HTML validation\n\nGenerated by \`node tests/e2e/validate-html.mjs\`. Validates \`index.html\` as rendered, plus the live DOM of ${pages} routes/states, using html-validate (recommended rules plus no-inline-style and prefer-native-element).\n\n**Result: ${unique.length === 0 ? 'no problems found' : `${unique.length} problem(s)`}**\n\n${unique.map((p) => `- ${p}`).join('\n')}\n`);
check(unique.length === 0, `html-validate: ${pages} pages, ${unique.length} problem(s)${unique.length ? '\n   - ' + unique.slice(0, 30).join('\n   - ') : ''}`);
await finish();
